{% set version = "2_6_6" %}
{% set ver = version.replace(".", "_") %}
{% set build = 0 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'mpich' %}
{% if mpi == "mpich" %}
  # prioritize mpich via build number
  {% set build = build + 100 %}
{% endif %}

{% set mpi_prefix = "mpi_" + mpi %}

{% if mpi == "mpi_serial" %}
  # we want to use the "nompi" versions of dependencies
  {% set mpi_dep_prefix = "nompi" %}
{% else %}
  {% set mpi_dep_prefix = mpi_prefix %}
{% endif %}

package:
  name: parallelio
  version: {{ version }}

source:
  url: https://github.com/NCAR/ParallelIO/archive/refs/tags/pio{{ ver }}.tar.gz
  sha256: e32e018a521d38c9424940c7cfa7e9b1931b605f3511ee7ab3a718b69faeeb04
  patches:
    - mpi-cmakelists.patch

build:
  number: {{ build }}
  skip: true  # [win]
  # add build string so packages can depend on mpi variants dependencies:
  # `PKG_NAME * mpi_mpich_*` for mpich
  # `PKG_NAME * mpi_*` for any mpi
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('parallelio', max_pin='x.x.x') }} {{ mpi_prefix }}_*
  ignore_run_exports_from:
    - netcdf-fortran

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - {{ mpi }}
    # these need to be listed twice so conda-smithy build picks up the pins
    - libnetcdf
    - libnetcdf * {{ mpi_dep_prefix }}_*
    - libpnetcdf  # [mpi != 'mpi_serial']
    - libpnetcdf * {{ mpi_dep_prefix }}_*  # [mpi != 'mpi_serial']
    - netcdf-fortran
    - netcdf-fortran * {{ mpi_dep_prefix }}_*

test:
  commands:
    - test -f ${PREFIX}/lib/libpioc${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libpiof${SHLIB_EXT}
    - test -f ${PREFIX}/include/pio.h

about:
  home: https://github.com/NCAR/ParallelIO
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A high-level Parallel I/O Library for structured grid applications
  dev_url: https://github.com/NCAR/ParallelIO
  doc_url: https://ncar.github.io/ParallelIO/

extra:
  recipe-maintainers:
    - zklaus
    - xylar
    - jedwards4b
